### PR TITLE
Improve maintainability

### PR DESCRIPTION
**Pull request by sudomakeinstall**

### CODE REVIEW

**Comment by unixabg** [comment]
Greetings,
First thank you for your code contribution. It will be a bit till I can examine and test the changes you are suggesting. I would like to ask if you have you tested your code against the latest raspbian lite? I ask since I always try to test any changes against the latest version with a pristine install. Again thank you for your submission.

**Comment by sudomakeinstall** [comment]
@unixabg 

No rush, please take your time!  I have it running using a clean install of the latest Raspbian Jesse -- I'm sorry, I did not test against Raspbian Jesse Lite.

I hope that the changes are helpful, but no worries either way--thank you very much for your work and for making this code available.

Best, and thanks,

--Davis

**Comment by unixabg** [comment]
Greetings,
Thank you for the prompt reply. Would you be able to test against Raspbian Stretch Lite, since it is the latest? If not no worries, I will test in a pristine environment soonish. fwiw: Most users only want a lite environment for this tool, so I only test against the latest lite, which is now Raspbian Stretch Lite.

**Comment by unixabg** [comment]
Greetings,
Thank you for the code. I have cherry-picked, tested with 2017-11-29-raspbian-stretch-lite, and made just a few minor adjustments. All appears in good order.

**Comment by sudomakeinstall** [comment]
@unixabg Thank you very much for testing and merging!  I'm sorry I never got around to testing with stretch-lite--if I ever end up submitting any more pull requests in the future, I will be sure to run this test first.

**Pull request closed without merging**
